/* groovylint-disable-next-line NglParseError */
pipeline {
    environment {
     registry = "muzij/frontend_app"
     registryCredential = 'docker_id'
     dockerImage = ''
     projectName = 'frontend_app'
    }
    
    agent any
    stages {
        stage('Cloning Git') {
            steps {
                git 'https://github.com/JackMj/u2_project_challenge/'
            }
        }
        stage('install dependencies') {
            steps {
                dir("coding/frontend/angularproject") {
                    sh "pwd"
                    sh "npm install"
                }
            }
        }
        stage('build project') {
            steps {
                dir("coding/frontend/angularproject") {
                    sh "pwd"
                    sh "ng build"
                }
            }
        }
        stage('build docker image') {
            steps {
                dir("coding/frontend/angularproject") {
                    script {
                    dockerImage = docker.build registry +":$BUILD_NUMBER"
                  } 
                }
            }
        }
        stage('Deploy Image') {
          steps{
            script {
              docker.withRegistry( '', registryCredential ) {
                dockerImage.push()
              }
            }
          }
        }
        stage('Remove Unused docker image') {
          steps{
            sh "docker rmi $registry:$BUILD_NUMBER"
          }
        }
    }
}
