pipeline {
    agent any
    tools { nodejs 'node' }
    stages {
        stage('Cloning Git') {
            steps {
                git 'https://github.com/JackMj/u2_project_challenge/tree/feature/backed/coding/backend/node_project'
            }
        }
        stage('Install dependencies') {
            steps {
                sh 'npm install'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'npm test'
            }
        }
        stage('Docker build') {
            steps {
                sh 'docker --version'
            }
        }
    }
}
